### ISSUE TITLE
Crash when crafting storage module

### ISSUE THREAD

**Issue by MinoCraft** [McJtyMods/RFToolsStorage#11]
Hello o/ 

I'm playing with the last version of RF Tools Mods for Mc 1.15.2 and Forge 31.1.77.
When I start to craft module storage, my game crash as you can see in this crash report:
Try to craft with Refined Storage:
https://www.dropbox.com/s/yqqzcytiyg7fglz/crash-2020-05-10_00.15.38-client.txt?dl=0

Try to craft with standard crafting table:
https://www.dropbox.com/s/wvwvmj3mw72vs0q/crash-2020-05-10_01.01.38-client.txt?dl=0

the crash occurs when the result appears in crafting table, I can't take module.
I,ve already storage with MK2 module installed and when I've opened storage block I don't crash.
Crash occurs only when you craft a new module =S
Otherwise, the rest of mods seems to be work fine ;)

Thanks in advance !

**Comment by Naheulf** [comment]
I narrowed the bug report.

### Description of the Issue
Client crash when showing storage module Tooltip (all tiers).

### Steps to Reproduce the Issue

1. Open a crafting table.
2. Open the vanilla recipe book.
3. Look for any storage module.
4. Hover storage module with mouse to display tooltip.

### Expected Behavior

Client should display tooltip.

### Actual Behavior

Client crash on both single-player and multi-player.

### Crash Report
https://github.com/Naheulf/Minecraft_mods_report/blob/master/MC%201.12.2/RFTools/RFToolsStorage/crash-2020-05-10_07.28.25-client.txt

### Debug Information
I copy here minimal informations from the crash report to help other players to find this issue from search engines.

#### Mod List: 
```
forge-1.15.2-31.1.77-client.jar Minecraft {minecraft@1.15.2 DONE}
forge-1.15.2-31.1.77-universal.jar Forge {forge@31.1.77 DONE}
mcjtylib-1.15-4.1.0-beta.jar McJtyLib {mcjtylib@1.15-4.1.0-beta DONE}
rftoolsbase-1.15-1.1.1-beta.jar RFToolsBase {rftoolsbase@1.15-1.1.1-beta DONE}
rftoolsstorage-1.15-1.1.1-beta.jar RFToolsStorage {rftoolsstorage@1.15-1.1.1-beta DONE}
```
#### Error and top of stacktrace:
```
Description: Rendering screen

java.lang.NullPointerException: Rendering screen
	at mcjty.rftoolsstorage.modules.modularstorage.items.StorageModuleItem.getStorage(StorageModuleItem.java:111) ~[?:1.15-1.1.1-beta] {re:classloading}
	at mcjty.rftoolsstorage.modules.modularstorage.items.StorageModuleItem.getAdvancedInfo(StorageModuleItem.java:89) ~[?:1.15-1.1.1-beta] {re:classloading}
	at mcjty.lib.builder.TooltipBuilder.addLines(TooltipBuilder.java:85) ~[?:1.15-4.1.0-beta] {re:classloading}
	at mcjty.lib.builder.TooltipBuilder.makeTooltip(TooltipBuilder.java:59) ~[?:1.15-4.1.0-beta] {re:classloading}
	at mcjty.rftoolsstorage.modules.modularstorage.items.StorageModuleItem.func_77624_a(StorageModuleItem.java:218) ~[?:1.15-1.1.1-beta] {re:classloading}
	...
```

**Comment by McJty** [comment]
Thanks for the detailed report. I'll check it out soon

**Comment by McJty** [comment]
Fixed for next release

**Comment by Naheulf** [comment]
Thank you
