### ISSUE TITLE
Modular Storage Crafting Not Working

### ISSUE THREAD

**Issue by rogerfleitas** [McJtyMods/RFToolsStorage#36]
![image](https://user-images.githubusercontent.com/60858379/106415179-6b7abd80-641c-11eb-9095-590f46822b5b.png)
![image](https://user-images.githubusercontent.com/60858379/106415189-6fa6db00-641c-11eb-9703-13fa6bdac752.png)

Upon attempting to craft through the modular storage menu or any linked tablets, it fails to craft the item. Attempted to craft through placing the recipe through JEI and through manual placement and neither were able to craft. Using only RFTools Storage, Base, and Power. Version 1.16.5. Storage version 2.0.8.

**Comment by jstansel** [comment]
I this problem in 1.18.1, using just the crafting in the modular storage. I will look for log messages and update if I find anything.

Update: I never saw any log messages, but I figured out a pattern. It avoids using the last of the ingredients, and only examines the first stack of ingredients. For example, to craft sticks, it works when there is a sinlge stack of 3 or more planks. A stack of 2 planks does not craft, and 3 stacks of 1 plank each does not craft.

**Comment by McJty** [comment]
Why is the storage locked though? I'm not sure I understand this report

**Comment by meson11** [comment]
I can confirm @jstansel 's observation with the storage scanner, too. If the first stack with an crafting ingredient has the exact amount of the crafting receipt ore less available, it doesn't craft. No matter if there are other stacks of the ingredient are present.

**Comment by McJty** [comment]
Sorry but I'm still confused. Can you tell me EXACTLY what you mean? Maybe with a screenshot?

**Comment by meson11** [comment]
First and second picture: crafting doesn't work.
Third picture: it is working.
It is quite annoying, because if you wan craft stacks of something it stops if the first stack in the row reachs the minimum amount of the recipe until you fill the first stack manually.
![crafting1](https://user-images.githubusercontent.com/22944649/155114457-e6fb4b4e-6293-4bc0-93df-0a3e5aef5bd5.jpg)
![crafting2](https://user-images.githubusercontent.com/22944649/155114469-a9c43c53-0130-4631-9775-91ae767910e2.jpg)
![crafting3](https://user-images.githubusercontent.com/22944649/155114478-fd6afc21-9d0e-44eb-a1e1-2933a918d945.jpg)

**Comment by meson11** [comment]
Actually you can't craft items, where you have only the exact amounts of ingredients.

**Comment by McJty** [comment]
Ok I'll check it out

**Comment by McJty** [comment]
Fixed
